name: hackint
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  STATE MANAGEMENT AND SL
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  flutter_dotenv: ^5.0.2

  #  NAVIGATION
  routemaster: ^1.0.1
  modal_bottom_sheet: ^2.0.0
  app_settings: ^4.1.8

  #  NETWORK
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  connectivity_plus: ^2.1.0
  flutter_cache_manager: ^3.3.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  flutter_local_notifications: ^12.0.4

  #  UTILS
  package_info_plus: ^1.4.1
  device_info: ^2.0.2
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^6.0.0
  intl: ^0.17.0
  uni_links: ^0.5.1
  dartz: ^0.10.1
  camera: ^0.10.0+4
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  url_launcher: ^6.0.20
  uuid: ^3.0.5
  scrollable_positioned_list: ^0.3.5
  flutter_slidable: ^2.0.0
  country_calling_code_picker: ^2.0.1
  extended_masked_text: ^2.3.1
  pin_code_fields: ^7.4.0
  phone_number: ^1.0.0
  collection: ^1.16.0
  flutter_contacts: ^1.1.5+1
  share_plus: ^6.3.0
  file_picker: ^5.2.5

  #  IMAGES
  cached_network_image: ^3.1.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.5
  flutter_svg: ^2.0.2

  # ICONS
  cupertino_icons: ^1.0.3

  # OTHER
  google_fonts: ^3.0.1
  dropdown_textfield: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.1.0
  injectable_generator: ^1.5.4
  flutter_launcher_icons: ^0.11.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/beluga_logo.png"
#   adaptive_icon_background: "assets/logo_background.png"
#   adaptive_icon_foreground: "assets/beluga_logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
